import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Button, Form } from 'react-bootstrap'
import { useState } from 'react'
import { doc, setDoc } from 'firebase/firestore';

import db from '@database';

export default function Home() {

  const [aggettivo, setAggettivo]=useState('');
  const [positivo, setPositivo]=useState(true);

  const addAggettivo = async () => {
    /**Aggiungere controllo su nome già inserito o non inserito nulla */
    await setDoc(doc(db,'aggettivo',aggettivo), {positivo: positivo});
    setAggettivo('');
  }

  
  return (
    <>
      <Head>
        <title>Bestiario</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Aggiungi un aggettivo</h1>
        <Form.Control type="name" className={`w-75 m-auto mt-3`}placeholder='Aggettivo'
        value={aggettivo} onChange={(e) => setAggettivo(e.target.value)}/>
       
       <Form.Check  type="switch" id="custom-switch" className='mt-3 mx-5'
       label="Check this switch" checked={positivo} onChange={()=>{console.log(positivo); setPositivo(!positivo);}}/>

       <Button className='mt-3 mx-5' onClick={()=>{addAggettivo()}}>Conferma</Button>
        
        {/*<Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />*/}
        
        
      </main>
    </>
  )
}
