import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Image from 'next/image'
import { Button } from 'react-bootstrap'
import Link from 'next/link'

export default function Home() {

  return (
    <>
      <Head>
        <title>Bestiario</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Bestiario</h1>
        <div className='d-flex flex-column w-100'>
          <Link href="./totem" className={`${styles.menuBtn} ${styles.menuBtnLeft} btn py-3`}>Trova il totem
          </Link>
          <Link href="./addAnimale" className={`${styles.menuBtn} ${styles.menuBtnRight} btn py-3 ms-auto`}>
            Aggiungi l'animale
          </Link>
          <Link href="./addAggettivo" className={`${styles.menuBtn} ${styles.menuBtnLeft} btn py-3`}>
            Aggiungi l'aggettivo
          </Link>
          
          <Link href="./" className={`${styles.menuBtn} ${styles.menuBtnRight} btn py-3 ms-auto`}>
            Controlla i dati
          </Link>
          
        </div>
        
        {/*<Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />*/}
        
        
      </main>
    </>
  )
}
