import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Image from 'next/image'
import { useState } from 'react';

import useStore from "@store";
import Link from 'next/link';

export default function Home() {

  /**CAMPI PER CHECKBOX */
  const animalSearch = useStore((state) => state.animalSearch);

  const [nome, setNome] = useState('');
  const [img, setImg] = useState('');
  const [famiglia, setFamiglia] = useState('');
  const [alimentazione, setAlimentazione] = useState('');
  const [intersection, setIntersection] = useState('');
  const [adjP, setAdjP] = useState('');
  const [adjN, setAdjN] = useState('');
  const [index, setIndex] = useState();
  const [info, setInfo] = useState('');
  const [totem, setTotem] = useState('');
  const [daimon, setDaimon] = useState('');

  return (
    <>
      <Head>
        <title>Bestiatio - Animali corrispondenti</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Animali corrispondenti</h1>
        <div className={styles.containerAnimals}>
          {animalSearch.map((item,i) => (
            <Image src={'/animal/'+item.nome.toLowerCase().replaceAll(' ','')+'.webp'} alt={item.nome} width={80} height={100} className={index===i ? 'active':''}
            onClick={()=>{
              setImg('/animal/'+item.nome.toLowerCase().replaceAll(' ','')+'.webp');
              setNome(item.nome);
              setFamiglia(item.famiglia);
              setAlimentazione(item.alimentazione);
              setIntersection(item.intersection);
              setAdjP(item.aggettiviP.toString().replaceAll(',',', '));
              setAdjN(item.aggettiviN.toString().replaceAll(',',', '));
              setInfo(item.hasOwnProperty('info') ? 'https://animalia.bio/it/'+item.info : item.altro);
              setDaimon(item.hasOwnProperty('daimon') ? item.daimon : '');
              setTotem(item.hasOwnProperty('totem') ? item.totem : '');
            }} key={item.nome}/>
          ))}
        </div>
        <div className={styles.containerAnimal}>
          {animalSearch.length===0 
            ? <p className='p-relative px-2 grayT'><small>Non sono stati trovati animali corrispondenti alla ricerca</small> </p>
            : <></>
          }
          { nome != '' ?
            <>
              <small className='me-1'>Aggettivi in comune: {intersection}</small><br/>
              <h2 className='lightT text-start h1 m-0'>{nome}</h2>
              <div>
                <div className={styles.divBtn}>
                  {daimon != '' ? <Link className='btn btnY my-1' href={'https://daimonismo.altervista.org/forum/viewtopic.php?'+daimon} target="_blank">Daimon</Link> : <></>}
                  {totem != '' ? <Link className='btn btnY my-1' href={'https://www.scoutsengidsenvlaanderen.be/totemzoeker/'+totem} target="_blank">Totem</Link> : <></> }
                  {info != '' ? <Link className='btn btnY my-1' href={info} target="_blank">Info</Link> : <></> }
                </div>
                <Image src={img} alt='' width={240} height={300} priority/>
              </div>
              <div  className='me-1'>
                <p className='m-0'>Famiglia: {famiglia}</p>
                <p className=''>Alimentazione: {alimentazione}</p>
                <p className='ps-1 lightT t-khand h5 m-0 text-start'>Aggettivi positivi</p>
                <p className='ps-2 text-start'>{adjP}</p>            
                <p className='ps-1 lightT t-khand h5 m-0 text-start'>Aggettivi negativi</p>
                <p className='ps-2 text-start'>{adjN}</p>
              </div>
            </>
            : <></>
          }
        </div>
        
        {/*<Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />*/}
        
        
      </main>
    </>
  )
}
