import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Image from 'next/image'

export default function Home() {

  console.log(ANIMAL);

  return (
    <>
      <Head>
        <title>Bestiatio - Animali corrispondenti</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Animali corrispondenti</h1>
        <div className={styles.containerAnimals}>
          <Image src="/animal/airone.webp" alt='alce' width={80} height={100}/>
          <Image src="/animal/ara.webp" alt='alce' width={80} height={100} className={styles.active}/>
          <Image src="/animal/arascarlatta.webp" alt='alce' width={80} height={100} />
          <Image src="/animal/alce.webp" alt='alce' width={80} height={100} />
        </div>
        <div className={styles.containerAnimal}>
          <small className='me-1'>Aggettivi in comune: 1</small><br/>
          <h2 className='lightT text-start h1 m-0'>Alce</h2>
          <Image src="/animal/alce.webp" alt='alce' width={240} height={300}/>
          <div  className='me-1'>
            <p className='m-0'>Famiglia: uccelli</p>
            <p className=''>Alimentazione: carnivoro</p>
            <p className='ps-1 lightT t-khand h5 m-0 text-start'>Aggettivi positivi</p>
            <p className='ps-2 text-start'>
            Ardito, Timido, Armonioso, Stonato, Assertivo, Irresoluto, Astuto, Ingenuo, Attento, Disattento, Ardito, Timido, Armonioso, Stonato, Assertivo, Irresoluto, Astuto, Ingenuo, Attento, Disattento
            </p>            
            <p className='ps-1 lightT t-khand h5 m-0 text-start'>Aggettivi negativi</p>
            <p className='ps-2 text-start'>
            Ardito, Timido, Armonioso, Stonato, Assertivo, Irresoluto, Astuto, Ingenuo, Attento, Disattento, Ardito, Timido, Armonioso, Stonato, Assertivo, Irresoluto, Astuto, Ingenuo, Attento, Disattento
            </p>
          </div>
        </div>
        
        {/*<Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />*/}
        
        
      </main>
    </>
  )
}
