import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Image from 'next/image'
import { Button } from 'react-bootstrap'

export default function Home() {

  return (
    <>
      <Head>
        <title>Bestiario</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Bestiario</h1>
        <div className='d-flex flex-column w-100'>
          <Button className={`${styles.menuBtn} ${styles.menuBtnLeft}`}>Trova il totem</Button>
          <Button className={`${styles.menuBtn} ${styles.menuBtnRight} ms-auto`}>Aggiungi l'animale</Button>
          <Button className={`${styles.menuBtn} ${styles.menuBtnLeft}`}>Aggiungi l'aggettivo</Button>
          <Button className={`${styles.menuBtn} ${styles.menuBtnRight} ms-auto`}>Controlla i dati</Button>
        </div>
        
        {/*<Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />*/}
        
        
      </main>
    </>
  )
}
